version: '3.8'

services:
  arangodb:
    image: arangodb:latest
    container_name: arangodb-food-factory
    environment:
      - ARANGO_ROOT_PASSWORD=admin123
    ports:
      - "8529:8529"
    volumes:
      - arangodb_data:/var/lib/arangodb3
      - arangodb_apps:/var/lib/arangodb3-apps

volumes:
  arangodb_data:
  arangodb_apps: